Repository argocd-diff-action/argocd-diff-action, pull requests merged in 2024-12, with the labels that each got.

#30 fix: warn and exit on no apps
  src/argocd/AppCollection.ts
  src/argocd/ArgoCDServer.ts
  src/main.ts
Labels: size/s

#78 ci: update all ci actions
  .github/workflows/checks.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/labeler.yml
  .github/workflows/lint-pr.yml
  .github/workflows/stale.yml
Labels: size/s

#79 feat: use node 20
  action.yml
Labels: size/xs

#80 feat: make source optional and use native fetch
  __tests__/argocd/AppCollection.test.ts
  __tests__/argocd/ArgoCDServer.test.ts
  __tests__/lib.test.ts
  commitlint.config.cjs
  dist/index.js
  jest.config.js
  jest.config.ts
  package-lock.json
  package.json
  src/Diff.ts
  src/argocd/App.ts
  src/argocd/AppCollection.ts
  src/argocd/ArgoCDServer.ts
  src/lib.ts
  src/main.ts
  tsconfig.json
Labels: size/xl

#81 feat: support plaintext protocol
  .nvmrc
  README.md
  __tests__/argocd/ArgoCDServer.test.ts
  action.yml
  dist/index.js
  src/argocd/ArgoCDServer.ts
  src/getActionInput.ts
  src/main.ts
Labels: size/m
